#!/usr/bin/env python3
"""Self-check for the plugin manifests in this repository.

Checks that every JSON manifest parses, that they all use the same plugin
name, version and MCP server URL, that every file a manifest references
exists, and that the generated rule files are present. Standard library only.

    python3 scripts/check.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

EXPECTED_NAME = "adloop"
EXPECTED_MCP_URL = "https://mcp.getadloop.com/mcp"

# Manifests that carry a plugin name and version.
MANIFESTS = [
    "plugin.json",
    ".claude-plugin/plugin.json",
    ".cursor-plugin/plugin.json",
    "gemini-extension.json",
]

# Files that declare MCP servers, inline or standalone.
MCP_SOURCES = [
    "mcp.json",
    ".mcp.json",
    ".cursor-plugin/plugin.json",
    "gemini-extension.json",
]

GENERATED_FILES = [
    "skills/adloop/SKILL.md",
    "rules/adloop.mdc",
    "GEMINI.md",
]
GENERATED_MARKER = "Generated by scripts/sync-from-adloop.py"


def load(relative: str, errors: list[str]) -> dict | None:
    path = REPO_ROOT / relative
    if not path.is_file():
        errors.append(f"{relative}: missing")
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        errors.append(f"{relative}: invalid JSON ({exc})")
        return None
    if not isinstance(data, dict):
        errors.append(f"{relative}: top level must be an object")
        return None
    return data


def server_urls(data: dict) -> list[str]:
    servers = data.get("mcpServers")
    if not isinstance(servers, dict):
        return []
    urls = []
    for config in servers.values():
        if isinstance(config, dict):
            url = config.get("url") or config.get("httpUrl")
            if url:
                urls.append(url)
    return urls


def referenced_paths(relative: str, data: dict) -> list[str]:
    paths = []
    if relative == ".claude-plugin/plugin.json":
        paths.append(data.get("icon"))
    elif relative == ".cursor-plugin/plugin.json":
        paths += [data.get("logo"), data.get("rules")]
    elif relative == "gemini-extension.json":
        paths.append(data.get("contextFileName"))
    elif relative == "plugin.json":
        interface = data.get("extensions", {}).get("com.openai", {}).get("interface", {})
        paths += [interface.get("logo"), interface.get("composerIcon")]
    return [path for path in paths if isinstance(path, str)]


def main() -> int:
    errors: list[str] = []
    loaded: dict[str, dict] = {}

    for relative in sorted(set(MANIFESTS + MCP_SOURCES)):
        data = load(relative, errors)
        if data is not None:
            loaded[relative] = data

    versions = {}
    for relative in MANIFESTS:
        data = loaded.get(relative)
        if data is None:
            continue
        if data.get("name") != EXPECTED_NAME:
            errors.append(f"{relative}: name is {data.get('name')!r}, expected {EXPECTED_NAME!r}")
        versions[relative] = data.get("version")
        for path in referenced_paths(relative, data):
            if not (REPO_ROOT / path).exists():
                errors.append(f"{relative}: references {path}, which doesn't exist")

    if len(set(versions.values())) > 1:
        listing = ", ".join(f"{name}={version}" for name, version in versions.items())
        errors.append(f"versions differ: {listing}")
    if any(version is None for version in versions.values()):
        errors.append("a manifest has no version")

    for relative in MCP_SOURCES:
        data = loaded.get(relative)
        if data is None:
            continue
        urls = server_urls(data)
        if not urls:
            errors.append(f"{relative}: declares no MCP server URL")
        for url in urls:
            if url != EXPECTED_MCP_URL:
                errors.append(f"{relative}: MCP URL {url}, expected {EXPECTED_MCP_URL}")

    for relative in GENERATED_FILES:
        path = REPO_ROOT / relative
        if not path.is_file():
            errors.append(f"{relative}: missing (run scripts/sync-from-adloop.py)")
        elif GENERATED_MARKER not in path.read_text(encoding="utf-8"):
            errors.append(f"{relative}: not generated by scripts/sync-from-adloop.py")

    if errors:
        print("Check failed:")
        for error in errors:
            print(f"  - {error}")
        return 1

    version = next(iter(versions.values()))
    print(
        f"OK: {len(loaded)} JSON files parse; name {EXPECTED_NAME}, "
        f"version {version}, MCP URL {EXPECTED_MCP_URL} everywhere."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
