#!/usr/bin/env python3
"""Regenerate the bundled AdLoop rules from the canonical AdLoop rules file.

The open-source AdLoop repository keeps one canonical rules file,
``.cursor/rules/adloop.mdc``. This script turns it into the three copies that
ship in this repository, rewritten for AdLoop Cloud:

  - ``skills/adloop/SKILL.md`` (+ ``skills/adloop/references/*.md``)
        Claude, Codex/ChatGPT and other Agent Skills clients
  - ``rules/adloop.mdc``    Cursor plugin rule
  - ``GEMINI.md``           Gemini CLI extension context

Never edit those files by hand: edit the canonical rules upstream, then run

    python3 scripts/sync-from-adloop.py            # rewrite the files
    python3 scripts/sync-from-adloop.py --check    # exit 1 if they are stale

By default the source is ``../adloop/.cursor/rules/adloop.mdc`` (a sibling
checkout of the AdLoop repository) and, when that doesn't exist, the file on
the AdLoop repository's ``main`` branch on GitHub. Pass ``--source`` with a
path or an https URL to use another copy.

The Cloud rewrite is a fixed list of exact replacements. If the upstream
wording changes so that a replacement no longer matches, or a new reference to
the self-hosted install appears, the script stops with an error instead of
shipping instructions that don't apply to AdLoop Cloud. Standard library only.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCAL_SOURCE = REPO_ROOT.parent / "adloop" / ".cursor" / "rules" / "adloop.mdc"
REMOTE_SOURCE = (
    "https://raw.githubusercontent.com/kLOsk/adloop/main/.cursor/rules/adloop.mdc"
)

SKILL_DIR = REPO_ROOT / "skills" / "adloop"
SKILL_FILE = SKILL_DIR / "SKILL.md"
CURSOR_RULE_FILE = REPO_ROOT / "rules" / "adloop.mdc"
GEMINI_FILE = REPO_ROOT / "GEMINI.md"

DASHBOARD = "the AdLoop Cloud dashboard at getadloop.com"

SKILL_FRONTMATTER = """\
---
name: adloop
description: >-
  Orchestration and safety rules for AdLoop Cloud's Google Ads, Reddit Ads and
  Google Analytics (GA4) tools, plus Search Console, Tag Manager and Merchant
  Center. Use whenever the user works on Google Ads, GA4, Reddit Ads or their
  tracking through AdLoop: performance reviews and account audits, search terms
  and negative keywords, keyword research and budget planning, new campaigns,
  ad groups or ads, conversion tracking and attribution checks, and before any
  AdLoop draft_* tool or confirm_and_apply call.
---
"""

CURSOR_FRONTMATTER = """\
---
description: AdLoop Cloud orchestration and safety rules for Google Ads, Reddit Ads and GA4 (Google Analytics). Apply when using AdLoop MCP tools, analyzing ad or analytics performance, or before any AdLoop draft_* or confirm_and_apply call.
globs:
alwaysApply: false
---
"""

GENERATED_NOTE = (
    "<!-- Generated by scripts/sync-from-adloop.py from the AdLoop rules "
    "(github.com/kLOsk/adloop, .cursor/rules/adloop.mdc). "
    "Do not edit by hand; run the script instead. -->\n"
)

CLOUD_NOTE = (
    "> **AdLoop Cloud edition.** These rules are for the hosted AdLoop server "
    "(`https://mcp.getadloop.com/mcp`). Google and Reddit connections, the "
    "maximum daily budget, the dry-run switch and the change log all live in "
    f"{DASHBOARD}. Nothing is configured on the user's machine."
)

# (old, new) pairs. Every ``old`` must occur in the source at least once.
CLOUD_REPLACEMENTS: list[tuple[str, str]] = [
    (
        "These rules teach you how to use them intelligently.",
        "These rules teach you how to use them intelligently.\n\n" + CLOUD_NOTE,
    ),
    (
        "means the Google Analytics Data API is not enabled in the Google Cloud "
        "project — tell the user to enable it; it is not a permissions or "
        "consent problem.",
        "means the Google Analytics Data API is not enabled for the Google "
        "connection — on AdLoop Cloud, tell the user to contact AdLoop support "
        "(hello@getadloop.com); it is not a permissions or consent problem.",
    ),
    (
        "Tell the user to delete `~/.adloop/token.json` and re-run any tool to "
        "trigger re-authorization. If tokens keep expiring weekly, the GCP "
        "consent screen needs to be published from \"Testing\" to \"In "
        "production\".",
        "Tell the user to reconnect Google under Settings → Google in "
        f"{DASHBOARD}.",
    ),
    (
        "are fixed by re-running the Reddit step of `adloop init` (self-hosted) "
        "or reconnecting under Settings → Reddit Ads (AdLoop Cloud);",
        f"are fixed by reconnecting under Settings → Reddit Ads in {DASHBOARD};",
    ),
    (
        "(none — uses config)",
        "(none — uses the connected Google account)",
    ),
    (
        "(none — uses MCC from config)",
        "(none — uses the connected Google account)",
    ),
    (
        "**GTM prerequisites:** the Tag Manager API must be enabled in the "
        "user's GCP project and their account needs at least Read access on the "
        "container. OAuth tokens granted before the GTM scope existed must be "
        "re-consented (delete `~/.adloop/token.json`, re-run any tool) — an "
        "`INSUFFICIENT_SCOPES` structured error means exactly that.",
        "**GTM prerequisites:** the connected Google account needs at least "
        "Read access on the container. A Google connection made before Tag "
        "Manager access was granted must be renewed (reconnect Google under "
        f"Settings → Google in {DASHBOARD}) — an `INSUFFICIENT_SCOPES` "
        "structured error means exactly that.",
    ),
    (
        "**GSC prerequisites:** the Search Console API must be enabled in the "
        "user's GCP project and their Google account needs access to the "
        "property in Search Console. Tokens granted before the GSC scope "
        "existed must re-consent (`INSUFFICIENT_SCOPES` error tells the user "
        "how).",
        "**GSC prerequisites:** the connected Google account needs access to "
        "the property in Search Console. A Google connection made before "
        "Search Console access was granted must be renewed by reconnecting "
        "Google (`INSUFFICIENT_SCOPES` error tells the user how).",
    ),
    (
        "`site_url` (falls back to `gsc.site_url` config)",
        "`site_url` (from `list_gsc_sites`)",
    ),
    (
        "(numeric; from list_merchant_accounts — optional when "
        "`merchant.account_id` is configured)",
        "(numeric; from list_merchant_accounts)",
    ),
    (
        "with its own connection (own OAuth app, no developer token, no "
        "approval process)",
        "with its own connection (connected under Settings → Reddit Ads in "
        f"{DASHBOARD})",
    ),
    (
        "(falls back to `reddit.ad_account_id` in the config)",
        "(falls back to the Reddit ad account chosen in the AdLoop Cloud "
        "dashboard)",
    ),
    (
        "`property_id` (falls back to config)",
        "`property_id` (falls back to the GA4 property chosen in the AdLoop "
        "Cloud dashboard)",
    ),
    (
        "- `require_dry_run: true` in config overrides `dry_run=false` — the "
        "user must change the config to allow real mutations.",
        "- The \"Allow dry-run only\" setting (Settings → Safety in "
        f"{DASHBOARD}) overrides `dry_run=false` while it is on — the user "
        "must switch it off there to allow real changes.",
    ),
    (
        "- `two_phase_apply: true` in config (always on for AdLoop Cloud) "
        "refuses",
        "- Two-phase apply (always on for AdLoop Cloud) refuses",
    ),
    (
        "- All operations (including dry runs) are logged to "
        "`~/.adloop/audit.log`.",
        "- All operations (including dry runs) are logged and shown on the Log "
        f"page of {DASHBOARD}.",
    ),
    (
        "Even then, `require_dry_run` in config may override this.",
        "Even then, the \"Allow dry-run only\" setting in the AdLoop Cloud "
        "dashboard may override this.",
    ),
    (
        "**Respect budget caps.** The config has max_daily_budget set. Never "
        "propose a campaign budget above this.",
        "**Respect budget caps.** The workspace has a maximum daily budget "
        "(`max_daily_budget`, set under Settings → Safety in the AdLoop Cloud "
        "dashboard; agencies can set one per client). Never propose a campaign "
        "budget above this.",
    ),
    (
        "If the user's codebase is accessible (Cursor native),",
        "If the user's codebase is accessible (for example in Cursor or Claude "
        "Code),",
    ),
    (
        "Must be ≤ `max_daily_budget` in config,",
        "Must be ≤ the workspace's `max_daily_budget`,",
    ),
    (
        "- **Customer ID**: Use the default from config (no need to ask)",
        "- **Customer ID**: Use the account chosen in the AdLoop Cloud "
        "dashboard (no need to ask)",
    ),
    (
        "- **Property ID**: Use the default from config (no need to ask)",
        "- **Property ID**: Use the property chosen in the AdLoop Cloud "
        "dashboard (no need to ask)",
    ),
]

# Anything matching these after the rewrite only makes sense for the
# self-hosted install, so the sync refuses to ship it.
SELF_HOSTED_MARKERS = [
    r"~/\.adloop",
    r"adloop init",
    r"install-rules",
    r"config\.yaml",
    r"\bGCP\b",
    r"\b(?:in|from|uses|to) config\b",
    r"\b[Tt]he config\b",
    r"falls back to config",
    r"`[a-z_]+\.[a-z_]+` config",
]

# Long reference sections that move out of SKILL.md into references/ so the
# skill loads lighter. Cursor and Gemini get the full text in one file.
REFERENCE_SECTIONS: list[tuple[str, str, str]] = [
    (
        "## GAQL Quick Reference",
        "references/gaql.md",
        "Read it before writing a `run_gaql` query.",
    ),
    (
        "## Geo & Language Targeting Reference",
        "references/geo-language-targeting.md",
        "Read it for geo target and language IDs beyond the common ones "
        "listed above.",
    ),
]


def read_source(source: str) -> str:
    if source.startswith("https://"):
        with urllib.request.urlopen(source, timeout=30) as response:
            return response.read().decode("utf-8")
    path = Path(source).expanduser()
    if not path.is_file():
        raise SystemExit(f"Rules file not found: {path}")
    return path.read_text(encoding="utf-8")


def strip_frontmatter(content: str) -> str:
    if not content.startswith("---"):
        return content
    end = content.index("\n---", 3)
    return content[end + 4 :].lstrip("\n")


def to_cloud(body: str) -> str:
    missing = [old for old, _ in CLOUD_REPLACEMENTS if old not in body]
    if missing:
        listing = "\n".join(f"  - {old[:100]}" for old in missing)
        raise SystemExit(
            "The upstream rules changed: these Cloud replacements no longer "
            f"match. Update CLOUD_REPLACEMENTS in {Path(__file__).name}.\n{listing}"
        )
    for old, new in CLOUD_REPLACEMENTS:
        body = body.replace(old, new)

    leftovers = []
    for number, line in enumerate(body.splitlines(), start=1):
        for marker in SELF_HOSTED_MARKERS:
            if re.search(marker, line):
                leftovers.append(f"  line {number}: {line.strip()[:120]}")
                break
    if leftovers:
        raise SystemExit(
            "The upstream rules contain self-hosted instructions that have no "
            f"Cloud rewrite yet. Add them to CLOUD_REPLACEMENTS.\n"
            + "\n".join(leftovers)
        )
    return body


def split_sections(body: str) -> list[str]:
    """Split the body into chunks, each starting at a level-2 heading."""
    parts = re.split(r"(?m)^(?=## )", body)
    return [part for part in parts if part]


def build_skill(body: str) -> dict[Path, str]:
    sections = split_sections(body)
    files: dict[Path, str] = {}
    kept: list[str] = []
    found = set()
    for section in sections:
        heading = section.splitlines()[0].strip()
        match = next((ref for ref in REFERENCE_SECTIONS if ref[0] == heading), None)
        if match is None:
            kept.append(section)
            continue
        found.add(heading)
        _, relative, hint = match
        files[SKILL_DIR / relative] = GENERATED_NOTE + "\n" + section.rstrip() + "\n"
        kept.append(f"{heading}\n\nSee [{relative}]({relative}). {hint}\n\n")

    missing = [ref[0] for ref in REFERENCE_SECTIONS if ref[0] not in found]
    if missing:
        raise SystemExit(
            "The upstream rules no longer have these sections: "
            + ", ".join(missing)
            + f". Update REFERENCE_SECTIONS in {Path(__file__).name}."
        )

    skill_body = "".join(kept).rstrip() + "\n"
    files[SKILL_FILE] = SKILL_FRONTMATTER + "\n" + GENERATED_NOTE + "\n" + skill_body
    return files


def render(source: str) -> dict[Path, str]:
    body = to_cloud(strip_frontmatter(read_source(source))).rstrip() + "\n"
    files = build_skill(body)
    files[CURSOR_RULE_FILE] = CURSOR_FRONTMATTER + "\n" + GENERATED_NOTE + "\n" + body
    files[GEMINI_FILE] = GENERATED_NOTE + "\n" + body
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--source",
        help="Path or https URL of adloop.mdc (default: sibling checkout, "
        "else GitHub main)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Don't write; exit 1 if any generated file is out of date",
    )
    args = parser.parse_args()

    source = args.source or (
        str(LOCAL_SOURCE) if LOCAL_SOURCE.is_file() else REMOTE_SOURCE
    )
    files = render(source)

    stale_references = sorted(
        path
        for path in (SKILL_DIR / "references").glob("*.md")
        if path not in files
    )

    if args.check:
        stale = [
            path
            for path, content in files.items()
            if not path.is_file() or path.read_text(encoding="utf-8") != content
        ]
        stale += stale_references
        if stale:
            print("Out of date (run scripts/sync-from-adloop.py):")
            for path in stale:
                print(f"  {path.relative_to(REPO_ROOT)}")
            return 1
        print(f"Generated rules are up to date with {source}")
        return 0

    for path in stale_references:
        path.unlink()
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    print(f"source: {source}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
